export function SwiperUnit({number}:{number:string}){
    return <div className="flex  text-white ">
        
        <div className="text-[96px] font-extrabold opacity-10  mr-[100px]">{number}</div>
       <div className="">
        lorem999
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci laudantium molestias nostrum quam cumque possimus sequi doloremque, voluptatem quod voluptatibus eius distinctio rerum, temporibus minima. Iste quis, veniam commodi odit ducimus laboriosam distinctio cupiditate autem adipisci ipsa facilis, nemo perspiciatis veritatis consequuntur facere dicta ut recusandae reprehenderit qui ullam, consectetur quod aliquid! Nihil aliquam numquam illum quod alias consequuntur ipsam neque ab sapiente mollitia? Minima necessitatibus dolorem ullam molestiae culpa? Porro ipsum veniam repellendus, ullam totam dicta quis, obcaecati mollitia officiis sint, magni ipsam fugit suscipit quisquam fugiat quidem sunt laborum facere quam perferendis non nam dolorem. Inventore, dignissimos optio soluta fugit similique distinctio quaerat dolore necessitatibus, facere, eos quas porro saepe deserunt id rerum sit deleniti odit laborum sunt neque nostrum! Doloremque eos placeat obcaecati dolore, commodi, cum eaque aperiam officia enim eius perspiciatis aliquid dolorum aliquam deserunt provident doloribus odio. Sint quae nesciunt modi harum ut enim, quis tempore quo tenetur iusto debitis unde recusandae a praesentium voluptatum alias dolores tempora dignissimos laborum. Quam repellat sunt, facilis, ad nisi dolores corrupti ipsum itaque quibusdam dolorum sint nobis blanditiis esse commodi. Esse laboriosam velit, nesciunt, amet quas consequuntur dolorum molestias nulla fugiat facere, maxime ducimus aliquid atque vitae ad!</div>
    <div className="">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt voluptates, possimus fugit enim recusandae culpa! Laboriosam laudantium debitis consequatur quod reiciendis! Numquam laboriosam doloribus autem eveniet maxime quaerat harum, pariatur architecto, odit corporis aut? Pariatur reprehenderit magni in, maiores hic reiciendis optio, qui, delectus voluptatum veniam officiis officia at distinctio? Voluptatem ipsum at deserunt eum. Quaerat asperiores velit ducimus ipsam deserunt, labore nesciunt rerum nam. Id fuga voluptatum non dignissimos beatae, perspiciatis similique minus blanditiis consectetur cumque provident aspernatur odit aperiam, tempora iste quidem animi quia numquam. Unde commodi veniam, odit laudantium voluptas earum veritatis libero quibusdam reiciendis ipsa quo?</div>
    </div>
}