import type { Metadata } from 'next'
export const metadata: Metadata = {
    title: 'Мои Проекты',
    description: 'Generated by create next app',
  }
  export default function ProjectsLayout({children}:{children:React.ReactNode}){
    return <>{children}</>
  }