import { Metadata } from "next"
import { SkillsNav } from "./units/skillsNav"
import { SoftSkills } from "./units/softSkills/SoftSkills"
export const metadata: Metadata = {
    title: 'Навыки',
    description: 'Generated by create next app',
  }
const SkillsLayout = ({children}:{children:React.ReactNode}) => {
  return (
    <div className="bg-[#1f1f1f] text-white min-h-screen pt-[159px] pb-[300px] flex">
        <div className="ml-[68px] border-l-[1px] border-white pl-[63px] pb-[64px]  w-[50%] bg-slate-300">
        <h1 className="text-[64px] font-bold pb-[70px]">МОИ НАВЫКИ</h1>
        <SkillsNav/>
        <main className="mt-[20px]">{children}</main>
        </div>
<SoftSkills/>
        </div>
  )
}

export default SkillsLayout